name = "EPB_AP"
uuid = "6eaf30bb-94d3-4aba-9730-811735af94f2"
authors = ["Devansh <devansh22@iisertvm.ac.in>"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
